### PR TITLE
Add preliminary support for type_traits

### PR DESCRIPTION
**Pull request by ldionne**

### CODE REVIEW

**Comment by pfultz2** [comment]
Thanks, I also opened an issue for bcm to add a property for warnings-as-error [here](https://github.com/boost-cmake/bcm/issues/5).

**Comment by pfultz2** [comment]
Just as a note, the type traits' tests depend on boost.move, which is missing. I think they work if you have an installed version of boost already.

**Comment by ldionne** [comment]
Hmm, so the boost dependency report does not show test dependencies, I guess? Damn, that's trickier.

**Comment by pfultz2** [comment]
Yea, I use my own script to find the dependencies. I just need to extend it to look in the test directory, [here](https://github.com/pfultz2/boost-cmake/blob/master/generate.py#L64). I am going to try to generate an initial test file with dependencies, and we can fill it in with tests.

**Pull request merged**
